from home.scraper.productspage import BuchererProductsPage, TourneauProductsPage, \
    CrownandcaliberProductsPage, BobswatchesProductsPage, \
    GoldsmithsProductsPage, WatchesofswitzerlandProductsPage, \
    JomashopProductsPage, MayorsProductsPage

from home.scraper.productdetails import BuchererProductDetails, \
    TourneauProductDetails, CrownandcaliberProductDetails, \
    BobswatchesProductDetails, GoldsmithsProductDetails, \
    WatchesofswitzerlandProductDetails, JomashopProductDetails, \
    MayorsProductDetails

# Mapping of domain to classes and reference key
domain_config = {
    'bucherer': {
        "ProductsPageClass": BuchererProductsPage,
        "ProductDetailsClass": BuchererProductDetails,
        "Brand": "Brand",
        "Model": "Collection",
        "Reference #": "Ref.",
        "SKU": "SKU",
        "Serial": "Futura Code.",
        "Origin": "Origin",
        "Gender": "Gender",
        "Material": "Case Material",
        "Color": "Dial Color",
        "Diameter": "Case Diameter",
        "Warranty": "Warranty",
        "Warranty Extension": "Warranty Extension",
        "Return Timeline":"Return Timeline",
        "Description": "Characteristics"
    },
    'tourneau': {
        "ProductsPageClass": TourneauProductsPage,
        "ProductDetailsClass": TourneauProductDetails,
        "Brand": "Brand",
        "Model": "Collection",
        "Reference #": "Manufacturer Reference #",
        "SKU": "Item Number",
        "Serial": "Serial",
        "Origin": "Country of Origin",
        "Gender": "Gender",
        "Material": "Case Material",
        "Color": "Dial Color",
        "Diameter": "Case Size",
        "Warranty": "Manufacturer Warranty",
        "Warranty Extension": "Warranty extension",
        "Return Timeline":"Return timeline",
        "Description": "Description"
    },
    'crownandcaliber': {
        "ProductsPageClass": CrownandcaliberProductsPage,
        "ProductDetailsClass": CrownandcaliberProductDetails,
        "Brand": "Brand",
        "Model": "Collection",
        "Reference #": "ref_no",
        "SKU": "SKU",
        "Serial": "Futura Code.",
        "Origin": "Origin",
        "Gender": "Gender",
        "Material": "Case Material",
        "Color": "Dial Color",
        "Diameter": "Case Size",
        "Warranty": "Warranty",
        "Warranty Extension": "Warranty extension",
        "Return Timeline":"Return timeline",
        "Description": "Description"
    },
    'bobswatches': {
        "ProductsPageClass": BobswatchesProductsPage,
        "ProductDetailsClass": BobswatchesProductDetails,
        "Brand": "Manufacturer",
        "Model": "Model Name",
        "Reference #": "Model Number",
        "SKU": "Item Number",
        "Serial": "Serial",
        "Origin": "Origin",
        "Gender": "Gender",
        "Material": "Case material",
        "Color": "Dial Color",
        "Diameter": "Case Diameter",
        "Warranty": "Warranty",
        "Warranty Extension": "Warranty extension",
        "Return Timeline":"Return Policy",
        "Description": "Description"
    },
    'goldsmiths': {
        "ProductsPageClass": GoldsmithsProductsPage,
        "ProductDetailsClass": GoldsmithsProductDetails,
        "Brand": "Brand",
        "Model": "Brand Collections",
        "Reference #": "Manufacturer Product Number",
        "SKU": "SKU",
        "Serial": "Product Code",
        "Origin": "Origin",
        "Gender": "Gender",
        "Gender": "Recipient",
        "Material": "Case Material",
        "Color": "Dial Colour",
        "Diameter": "Diameter",
        "Warranty": "Guarantee",
        "Warranty Extension": "Warranty extension",
        "Return Timeline":"14 days",
        "Description": "Description"
    },
    'watchesofswitzerland': {
        "ProductsPageClass": WatchesofswitzerlandProductsPage,
        "ProductDetailsClass": WatchesofswitzerlandProductDetails,
        "Brand": "Brand",
        "Model": "Brand Collections",
        "Reference #": "Manufacturer Product Number",
        "SKU": "SKU",
        "Serial": "Product Code",
        "Origin": "Origin",
        "Gender": "Gender",
        "Gender": "Recipient",
        "Material": "Case Material",
        "Color": "Dial Color",
        "Diameter": "Diameter",
        "Warranty": "Guarantee",
        "Warranty Extension": "Warranty extension",
        "Return Timeline":"14 days",
        "Description": "Description"
    },
    'jomashop': {
        "ProductsPageClass": JomashopProductsPage,
        "ProductDetailsClass": JomashopProductDetails,
        "Brand": "Brand",
        "Model": "Collection Name",
        "Reference #": "ref_no",
        "SKU": "Jomashop Sku",
        "Serial": "Upc Code",
        "Origin": "Watch Label",
        "Gender": "Gender",
        "Material": "Case Material",
        "Color": "Dial Color",
        "Diameter": "Case Size",
        "Warranty": "Warranty",
        "Warranty Extension": "Warranty extension",
        "Return Timeline":"14 days",
        "Description": "Description"
    },
    'mayors': {
        "ProductsPageClass": MayorsProductsPage,
        "ProductDetailsClass": MayorsProductDetails,
        "Brand": "Brand",
        "Model": "Brand Collections",
        "Reference #": "Manufacturer Product Number",
        "SKU": "SKU",
        "Serial": "Product Code",
        "Origin": "Origin",
        "Gender": "Gender",
        "Gender": "Recipient",
        "Material": "Case Material",
        "Color": "Dial Color",
        "Diameter": "Diameter",
        "Warranty": "Guarantee",
        "Warranty Extension": "Warranty extension",
        "Return Timeline":"14 days",
        "Description": "Description"
    },
}